
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mo
 */
public class hangmanGuessjframe extends javax.swing.JFrame {
    String FindWord ="dog:country:mouse:cater:money:someday";
    int charPos = 0;
    int Incorrect = 0, correct = 0;
    String[] wordsAsArray = FindWord.split(":");
    int index = new Random().nextInt(wordsAsArray.length);
    String randomWord = wordsAsArray[index];
    int  lengthword = randomWord.length() ;
    public hangmanGuessjframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        char0 = new javax.swing.JLabel();
        char1 = new javax.swing.JLabel();
        char2 = new javax.swing.JLabel();
        char4 = new javax.swing.JLabel();
        char7 = new javax.swing.JLabel();
        char3 = new javax.swing.JLabel();
        char5 = new javax.swing.JLabel();
        char6 = new javax.swing.JLabel();
        char8 = new javax.swing.JLabel();
        char9 = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        tryLetter = new javax.swing.JButton();
        lbIncorrect = new javax.swing.JLabel();
        MyMessages = new javax.swing.JLabel();
        btDisplay = new javax.swing.JButton();
        showIndex = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        char0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char0.setText("X");
        getContentPane().add(char0, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 11, 30, 50));

        char1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char1.setText("X");
        getContentPane().add(char1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 11, 30, 50));

        char2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char2.setText("X");
        getContentPane().add(char2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 11, 30, 50));

        char4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char4.setText("X");
        getContentPane().add(char4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 11, 30, 50));

        char7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char7.setText("X");
        getContentPane().add(char7, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 11, 30, 50));

        char3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char3.setText("X");
        getContentPane().add(char3, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 11, 30, 50));

        char5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char5.setText("X");
        getContentPane().add(char5, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 11, 30, 50));

        char6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char6.setText("X");
        getContentPane().add(char6, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 11, 30, 50));

        char8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char8.setText("X");
        getContentPane().add(char8, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 11, 30, 50));

        char9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char9.setText("X");
        getContentPane().add(char9, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 11, 30, 50));

        txtInput.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtInput.setText("e");
        getContentPane().add(txtInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 60));

        tryLetter.setText("guess word");
        tryLetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryLetterActionPerformed(evt);
            }
        });
        getContentPane().add(tryLetter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 120, 50));

        lbIncorrect.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbIncorrect.setText("0");
        getContentPane().add(lbIncorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 110, 50));

        MyMessages.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MyMessages.setText("look here");
        getContentPane().add(MyMessages, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 340, 80));
        getContentPane().add(btDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 540, 410));
        getContentPane().add(showIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 180, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents


//int lengtha =FindWord.length() ;
  
//     int lengththis = randomWord.length ;
     
 
       
       
       
   
    private void tryLetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryLetterActionPerformed
        // TODO add your handling code here:
       String a = Integer.toString(index) ;
     showIndex.setText(a);
       
      for(int k=0 ; k<lengthword; k++){
        
           if (lengthword == 3){
           char0.setVisible(true);
           char1.setVisible(true);
           char2.setVisible(true);
           char3.setVisible(false);
           char4.setVisible(false);
           char5.setVisible(false);
           char6.setVisible(false);
           char7.setVisible(false);
           char8.setVisible(false);
           char9.setVisible(false);
           
       } 
           if (lengthword == 4){
           char0.setVisible(true);
           char1.setVisible(true);
           char2.setVisible(true);
           char3.setVisible(true);
           char4.setVisible(false);
           char5.setVisible(false);
           char6.setVisible(false);
           char7.setVisible(false);
           char8.setVisible(false);
           char9.setVisible(false);
           
       } 
            if (lengthword == 5){
           char0.setVisible(true);
           char1.setVisible(true);
           char2.setVisible(true);
           char3.setVisible(true);
           char4.setVisible(true);
           char5.setVisible(false);
           char6.setVisible(false);
           char7.setVisible(false);
           char8.setVisible(false);
           char9.setVisible(false);
           
       } 
                 if (lengthword == 6){
           char0.setVisible(true);
           char1.setVisible(true);
           char2.setVisible(true);
           char3.setVisible(true);
           char4.setVisible(true);
           char5.setVisible(true);
           char6.setVisible(false);
           char7.setVisible(false);
           char8.setVisible(false);
           char9.setVisible(false);
           
       } 
           
              if (lengthword== 7){
           char0.setVisible(true);
           char1.setVisible(true);
           char2.setVisible(true);
           char3.setVisible(true);
           char4.setVisible(true);
           char5.setVisible(true);
           char6.setVisible(true);
           char7.setVisible(false);
           char8.setVisible(false);
           char9.setVisible(false);
           
       } 
               if (lengthword == 8){
           char0.setVisible(true);
           char1.setVisible(true);
           char2.setVisible(true);
           char3.setVisible(true);
           char4.setVisible(true);
           char5.setVisible(true);
           char6.setVisible(true);
           char7.setVisible(true);
           char8.setVisible(false);
           char9.setVisible(false);
           
       }   
         if (lengthword == 9){
           char0.setVisible(true);
           char1.setVisible(true);
           char2.setVisible(true);
           char3.setVisible(true);
           char4.setVisible(true);
           char5.setVisible(true);
           char6.setVisible(true);
           char7.setVisible(true);
           char8.setVisible(true);
           char9.setVisible(false);
           
       }   
          if (lengthword == 10){
           char0.setVisible(true);
           char1.setVisible(true);
           char2.setVisible(true);
           char3.setVisible(true);
           char4.setVisible(true);
           char5.setVisible(true);
           char6.setVisible(true);
           char7.setVisible(true);
           char8.setVisible(true);
           char9.setVisible(true);
           
       }   
      }
              
       
        
        String letter = txtInput.getText();
        charPos = randomWord.indexOf(letter);
        
          for (int i=0 ;i<=9;i++){ 
         charPos = randomWord.indexOf(letter,charPos + 1 );
              
        if (charPos == 0) char0.setText(letter);
        if (charPos == 1) char1.setText(letter);
        if (charPos == 2) char2.setText(letter);
        if (charPos == 3) char3.setText(letter);
        if (charPos == 4) char4.setText(letter);
        if (charPos == 5) char5.setText(letter);
        if (charPos == 6) char6.setText(letter);
        if (charPos == 7) char7.setText(letter);
        if (charPos == 8) char8.setText(letter);
        if (charPos == 9) char9.setText(letter);
        
         }
         
        charPos = randomWord.indexOf(letter);
          MyMessages.setText("position is " + charPos );
         
          if (charPos < 0 ){
                    
                   Incorrect = Incorrect  + 1 ;
                    
                    String w = Integer.toString(Incorrect);
                    
                    lbIncorrect.setText(w) ;
                  
           if(Incorrect>=6){
              lbIncorrect.setText("7");
          } 
          
           
         }
          
          
           
          if(charPos !=-1){
               correct= correct + 1 ;
              if(correct==lengthword){
                  MyMessages.setText("you have Won !!!!!!") ;
              }
                  
          }
          
          
          
            
                  if (Incorrect == 1 ) {
                btDisplay.setIcon(new javax.swing.ImageIcon("Images/hangman1.png"));
                  }
                  
                    if (Incorrect == 2 ) {
                btDisplay.setIcon(new javax.swing.ImageIcon("Images/hangman2.png"));
                  }
                    
                      if (Incorrect == 3 ) {
                btDisplay.setIcon(new javax.swing.ImageIcon("Images/hangman3.png"));
                  }
                      
                        if (Incorrect == 4 ) {
                btDisplay.setIcon(new javax.swing.ImageIcon("Images/hangman4.png"));
                  }
                        
                          if (Incorrect == 5 ) {
                btDisplay.setIcon(new javax.swing.ImageIcon("Images/hangman5.png"));
                  }
                          
                            if (Incorrect == 6) {
                btDisplay.setIcon(new javax.swing.ImageIcon("Images/hangman6.png"));
                  }
                            
                              if (Incorrect == 7 ) {
                btDisplay.setIcon(new javax.swing.ImageIcon("Images/hangman7.png"));
                MyMessages.setText("you have lost !!!!!!") ;
                  }
     
                              
                              
                              
 

    }//GEN-LAST:event_tryLetterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hangmanGuessjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hangmanGuessjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hangmanGuessjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hangmanGuessjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hangmanGuessjframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MyMessages;
    private javax.swing.JButton btDisplay;
    private javax.swing.JLabel char0;
    private javax.swing.JLabel char1;
    private javax.swing.JLabel char2;
    private javax.swing.JLabel char3;
    private javax.swing.JLabel char4;
    private javax.swing.JLabel char5;
    private javax.swing.JLabel char6;
    private javax.swing.JLabel char7;
    private javax.swing.JLabel char8;
    private javax.swing.JLabel char9;
    private javax.swing.JLabel lbIncorrect;
    private javax.swing.JLabel showIndex;
    private javax.swing.JButton tryLetter;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
